### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by glenncol** [TRaSH-/Guides#550] opened 2022-04-01 00:36 UTC
Synology Automated script.

When running the automated script I received the following error and the script halted

"ERROR get "Https://cr.htoio.dev/v2/"; x509:certificate has expired or is not yet valid"

![image](https://user-images.githubusercontent.com/102772486/161172217-f2974b74-a739-4920-a305-045a76498512.png)

**Comment by TRaSH-** [comment] 2022-04-01 19:21
@bokkoman

**Comment by bokkoman** [comment] 2022-04-01 19:29
Looks like a certificate error?
What DSM version are you running?

**Comment by bokkoman** [comment] 2022-04-01 19:34
Might have found a solution.
But first try this, see if there's an update for your Docker app in Package Center.

If not, try running this command:
`sudo docker-machine regenerate-certs --client-certs`

**Comment by angrycuban13** [comment] 2022-04-01 19:36
@glenncol do you have an ad blocker in your network?

**Comment by glenncol** [comment] 2022-04-02 01:24
> Looks like a certificate error? What DSM version are you running?

Hi I am running DSM 6.2-23739

**Comment by glenncol** [comment] 2022-04-02 01:33
> sudo docker-machine regenerate-certs --client-certs

Hi, i checked and there were no updates, I ran the above command and got "Sudo docker-machine: command not found"

**Comment by glenncol** [comment] 2022-04-02 01:33
> @glenncol do you have an ad blocker in your network?

Hi, I don't have any ad blockers loaded as yet

**Comment by bokkoman** [comment] 2022-04-02 06:13
Might be some sort of incorrect time issue on your end?
You can try restarting docker, or maybe reinstalling (from package center).
The command to regenerate certs is deprecated.

Maybe if you open the yml file that was downloaded.

Maybe a simple retrying the command to install the containers will work now.

`cd /volume1/docker/appdata`
`sudo docker-compose up -d`

**Comment by angrycuban13** [comment] 2022-04-02 14:13
> > @glenncol do you have an ad blocker in your network?
> 
> 
> 
> Hi, I don't have any ad blockers loaded as yet

What does your network look like in terms of topology? What router/firewall are you using?

**Comment by glenncol** [comment] 2022-04-03 03:10
Hi all , i really appreciate all the help here

I have tried uninstalling docker and reinstalling, I have retried the commands fir the auto file and also doing it the manual way and getts stuck on the same thing.

Net work is an Asus AX88U with an additional Unifi AC Litte, a few HP Proliant switches here and there, 2 time HP Gen 8 Microservers. HP N54L microserver, 3 PC's x 2 laptops, 3 Ipads, and Apple TV. Standard firewall on the router

**Comment by angrycuban13** [comment] 2022-04-03 03:46
I would check if that ASUS router come with some sort of adblocker, I'm going to assume no but it doesn't hurt.

**Comment by glenncol** [comment] 2022-04-03 04:02
> I would check if that ASUS router come with some sort of adblocker, I'm going to assume no but it doesn't hurt.

Hi, yeah the Asus does not have Ad blocking built-in, the only Ad blocking I use is ion my browser

**Comment by bakerboy448** [comment] 2022-04-03 13:01
Asus does have that trend micro protection crap that can cause issues though

**Comment by angrycuban13** [comment] 2022-04-03 14:15
> > I would check if that ASUS router come with some sort of adblocker, I'm going to assume no but it doesn't hurt.
> 
> 
> 
> Hi, yeah the Asus does not have Ad blocking built-in, the only Ad blocking I use is ion my browser
> 
> 
> 
> On Both the Auto scrip and the Manul one it seems to bomb out while at either pulling or installing Radarr, its strange 

Can you try not doing it on Synology just to test? I suspect the issue is the Synology OS.

**Comment by bokkoman** [comment] 2022-04-03 14:26
> 
> Can you try not doing it on Synology just to test? I suspect the issue is the Synology OS.

What about pinging the server?
I have no problems with this on my Synology.

You could also try the linuxserver images.
If you open the `docker-compose.yml` and edit the image locations from hotio to linuxserver (`image: lscr.io/linuxserver/radarr`)
and try to compose up again.

**Comment by glenncol** [comment] 2022-04-04 00:48
> image: lscr.io/linuxserver/radarr

I ran a rebuild on the Synology and tried from scratch disabling all the AI protection on the router with the same isssue

**Comment by glenncol** [comment] 2022-04-04 00:50
> Asus does have that trend micro protection crap that can cause issues though

Hi yeah I rebuilt the Synology and retried with all AI protection turned off and had the same issue

**Comment by glenncol** [comment] 2022-04-04 00:50
> > > I would check if that ASUS router come with some sort of adblocker, I'm going to assume no but it doesn't hurt.
> > 
> > 
> > Hi, yeah the Asus does not have Ad blocking built-in, the only Ad blocking I use is ion my browser
> > On Both the Auto scrip and the Manul one it seems to bomb out while at either pulling or installing Radarr, its strange
> 
> Can you try not doing it on Synology just to test? I suspect the issue is the Synology OS.

I don't really have anything else with Docker installed

**Comment by glenncol** [comment] 2022-04-04 00:53
> > Can you try not doing it on Synology just to test? I suspect the issue is the Synology OS.
> 
> What about pinging the server? I have no problems with this on my Synology.
> 
> You could also try the linuxserver images. If you open the `docker-compose.yml` and edit the image locations from hotio to linuxserver (`image: lscr.io/linuxserver/radarr`) and try to compose up again.

Sorry what server are you referring to?

I rebuilt the Synology NAS and edited the  yml file to include the image location you mentioned and had exactly the same result except this time mentioned the new server location

**Comment by glenncol** [comment] 2022-04-04 02:43
Just to add to the above, I rebuilt another one of my NAS units using a different version of DSM and the same issue was present

**Comment by bokkoman** [comment] 2022-04-04 05:20
> 
see if you can run this command without error:
`sudo docker pull hotio/radarr`

if that fails, try this:

`sudo docker pull lscr.io/linuxserver/radarr`

**Comment by glenncol** [comment] 2022-04-04 05:24
> sudo docker pull hotio/radarr

Hi, yes the first command pulled the image

**Comment by bokkoman** [comment] 2022-04-04 05:27
> > sudo docker pull hotio/radarr
> 
> Hi, yes the first command pulled the image

Then you have to manually edit the docker-compose.yml and remove the `cr.hotio.dev` from the image locations.

I just read your version number for DSM, it is old. The Root Certificates have expired.
See if you can update to DSM7 (https://www.synology.com/en-global/support/download)

**Comment by glenncol** [comment] 2022-04-04 05:46
> > > sudo docker pull hotio/radarr
> > 
> > 
> > Hi, yes the first command pulled the image
> 
> Then you have to manually edit the docker-compose.yml and remove the `cr.hotio.dev` from the image locations. So it ends up like `image: hotio/radarr`.
> 
> I just read your version number for DSM, it is old. The Root Certificates have expired. See if you can update to DSM7 (https://www.synology.com/en-global/support/download)

Hey bokkoman

I will give that a go as soon as I get home, as far as updating to DSM7 I am running Synology OS on my HP microserver, as far as I know, there is Xpenology DSM 7 version as yet

**Comment by bokkoman** [comment] 2022-04-04 06:05
> Hey bokkoman
> 
> I will give that a go as soon as I get home, as far as updating to DSM7 I am running Synology OS on my HP microserver, as far as I know, there is Xpenology DSM 7 version as yet

Ah I get it now. Xpenelogy is behind in version numbers.
I think i found a fix for expired root certs, take a loot at their forums here:

https://xpenology.com/forum/topic/49308-how-to-update-lets-encrypt-root-certificate/?do=findComment&comment=222665

**Comment by glenncol** [comment] 2022-04-05 01:48
> hotio/radarr

Wow ok, first off thank you very much for all your time on this

I ran the update cert commands from the Xpenology forum and restarted the server

I tried downloading the auto scripts again but they were not available, so I followed the manual path, I edited the file to replace the image location for radar as you suggested. 
This time when running the command to create the AppData folders I received a permission denied error so I created them manually, I finally ran the docker-compose file and it installed radarr , sonarr and bazarr but I received the following error while installing Plex.

![image](https://user-images.githubusercontent.com/102772486/161663238-7ed44e32-ca2c-477e-8ba6-76538e5b5b6a.png)

**Comment by bokkoman** [comment] 2022-04-05 10:33
> 

Your system does not have an Intel CPU with Quick Sync?
The /dev/dri is where the drivers are located for this, since you do not have it, it errors out.

If you open the compose you find these 2 lines you need to comment out or delete.

`    devices:                                        # optional: if you have a Syno with an Intel CPU with quicksync and want hardware transcoding (only with Plex Pass)
      - /dev/dri:/dev/dri                           # optional: if you have a Syno with an Intel CPU with quicksync and want hardware transcoding (only with Plex Pass)`

Run the `sudo docker-compose up -d` (in the correct folder of course) command again after that.

**Comment by TRaSH-** [comment] 2022-04-05 11:14
You could join our discord support channel.
Being it's starting to become a general support thread now, and not related anymore on the initial issue.
So I'm considering to close this issue.
Support can be asked in the discord channel.
Would be much faster also.

**Closed by TRaSH-** 2022-04-05 11:14 UTC
Labels: Type: Bug

**Comment by o42o** [comment] 2022-05-04 04:01
> If that both didn't work, try disabling adblockers like pihole or adguard.

I add an answer for those who might have the same problem. 

I got the same error on the first try: "ERROR get "https://cr.htoio.dev/v2/"; x509:certificate has expired or is not yet valid"

I am using NextDNS and by adding to the whitelist "hotio.dev" everything worked fine on the second try!
